SECRET_KEY='dev'
HISTOANNOT_DELEGATE_DZI=False
HISTOANNOT_PUBLIC_NAME='PICSL Histology Annotation Server (PHAS)'
HISTOANNOT_SERVER_MODE='master'
PURECSS_RESPONSIVE_GRIDS=True
PURECSS_USE_CDN=True
PURECSS_USE_MINIFIED=True